name: CI Build

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - 'include/**'
      - 'src/**'
      - 'Makefile'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - 'include/**'
      - 'src/**'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt-get install -y libx11-dev libxfixes-dev libxrandr-dev libxft-dev libfreetype-dev

      - name: build
        run: make

      - name: run tests
        run: ./bin/run_tests
